### ISSUE TITLE
Override props using getChildrenByTypeDeep

### ISSUE THREAD

**Issue by davegomez** [TheSpicyMeatball/react-nanny#12]
Is it possible to override or add new props to the children returned by `getChildrenByTypeDeep` or is there any other way to get those children and override the props at the same time?

I'm trying to use `getChildrenByTypeDeep` and `overridePropsDeep` but I'm not getting it right.

Thank you for any help you can provide.

**Comment by TheSpicyMeatball** [comment]
It sounds like you want something like this...?

```
const filtered = getChildrenByTypeDeep(children, 'MyComponentType');
const filteredAndUpdated = filtered.map(component => overridePropsDeep(component, () => ({ active: true }));
```
...or...
```
const filtered = getChildrenByTypeDeep(children, 'MyComponentType');
const filteredAndUpdated = overridePropsDeep(filtered, () => ({ active: true });
```
Does that help?
