### ISSUE TITLE
Support for children function?

### ISSUE THREAD

**Issue by pixelkritzel** [TheSpicyMeatball/react-nanny#13]
This looks like a great tool. But I can't find my children. My guess is it is because they are returned from [children functions](https://medium.com/merrickchristensen/function-as-child-components-5f3920a9ace9).

Does anyone know if this use case is or should be supported?

**Comment by TheSpicyMeatball** [comment]
Hello,

I've now added support for functions as children in the latest (`v2.14.0`). Thank you for bringing this to my attention! 

Please reopen the ticket if you have any issues.
