### ISSUE TITLE
There is a crash if one of the children element is `null`

### ISSUE THREAD

**Issue by eugenet8k** [TheSpicyMeatball/react-nanny#18]
If React markup has a child under the condition

```
<div>
      <div>Header</div>
      {description && <p>{description}</p>}
</div>
```

the result children will be `[element, null]` and that will crash the lib.

**Comment by TheSpicyMeatball** [comment]
@eugenet8k 

Is there a specific function in the lib that you can point me to that has this issue?

**Comment by blabute** [comment]
Hello! I came to this issue since I ran into it as well. I was using the `getChildByTypeDeep` function.

**Comment by blabute** [comment]
FWIW, if I remove the filter part of [this line](https://github.com/TheSpicyMeatball/react-nanny/blob/main/src/getChildByType/index.deep.test.js#L31) from the tests and add a test case like `{ type: 'div', props: { children: [null, {type: 'div'}] } },` to the children in `src/getChildByType/index.deep.test.js`, I get this error as well.

Can you explain why https://github.com/TheSpicyMeatball/react-nanny/blob/main/src/getChildByType/index.deep.test.js#L31 is added to the tests and not something we handle in the src?

**Comment by blabute** [comment]
I took a stab at correcting this [here](https://github.com/TheSpicyMeatball/react-nanny/pull/19). Please let me know what you think!

**Comment by blabute** [comment]
@TheSpicyMeatball not sure if you got notified of this since it's a closed issue, thanks!

**Comment by blabute** [comment]
In case anyone else stumbles upon this issue, our team has decided to use [react-children-utilities](https://www.npmjs.com/package/react-children-utilities) instead. It supports our needs, has more stars, has more downloads, is smaller, and supports React 15 - 18.
