### ISSUE TITLE
Warning: React does not recognize the `__TYPE` prop on a DOM element

### ISSUE THREAD

**Issue by kozlikov** [TheSpicyMeatball/react-nanny#2]
Hello!

Unfortunately, the reagent issues an inconvenient warning and is very annoying when developing if additional other errors or warnings appear.

```
Warning: React does not recognize the `__TYPE` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `__type` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

It would be great if we fix this behavior...

**Comment by TheSpicyMeatball** [comment]
@kozlikov  `react-nanny` doesn't add any props to any components so I'm guessing that you might have it bleeding through a rest prop.

Where your component is possibly something like this:

```
import React from 'react';

const Hello = ({ ...other }) => <div {...other}>Hello World!</div>;

Hello.defaultProps = {
  __TYPE: 'Hello',
};
```

Where it should be something like this:

```
import React from 'react';

const Hello = ({ __TYPE, ...other }) => <div {...other}>Hello World!</div>;

Hello.defaultProps = {
  __TYPE: 'Hello',
};
```
(notice that `__TYPE` is an unused constant not included in the render)

Let me know if that helps. Otherwise, if you could post some code of your usage, I'd be more than happy to take a look.

**Comment by kozlikov** [comment]
Yes, of course, please, here's an example in the codebox:

https://codesandbox.io/s/exmaple31212020-whkt8?file=/src/App.js

![image](https://user-images.githubusercontent.com/13614707/103363318-dc505200-4acb-11eb-81e5-83a5e0c9f1fe.png)

**Comment by TheSpicyMeatball** [comment]
Change this line (line #6)...

`const { children, ...other } = props;`

To this...

`const { children, __TYPE, ...other } = props;`

That will keep `__TYPE` from ending up in your DOM.

**Comment by kozlikov** [comment]
> Change this line (line #6)...
> 
> `const { children, ...other } = props;`
> 
> To this...
> 
> `const { children, __TYPE, ...other } = props;`
> 
> That will keep `__TYPE` from ending up in your DOM.

Oh, with this react, that I already forgot about the default html tags and their parameters))

Thank you very much!!!

**Comment by TheSpicyMeatball** [comment]
You got it!
