### ISSUE TITLE
getChildByType should accept a single component

### ISSUE THREAD

**Issue by tyteen4a03** [TheSpicyMeatball/react-nanny#4]
Most of the time I am not interested in finding a child by multiple types. The signature for `getChildByType()` (and similar) should allow for passing only one component / string into the `type` parameter.

**Comment by TheSpicyMeatball** [comment]
@tyteen4a03 Thanks for the suggestion. I've added that functionality into the `ByType` utils. So now you can pass in a single item as well as an array. 

Install v2.8.0
