### ISSUE TITLE
Get children which are elements

### ISSUE THREAD

**Issue by LoganDark** [TheSpicyMeatball/react-nanny#5]
Makes sure all children were made by `React.createElement`, i.e. you can safely access their props and component and stuff. I'm making a component that wants to preserve props of its children, but modify a couple (`style` and `className`).

**Comment by TheSpicyMeatball** [comment]
I'm not sure I follow. Can you provide a simple code example of what you're trying to accomplish?

**Comment by LoganDark** [comment]
> I'm not sure I follow. Can you provide a simple code example of what you're trying to accomplish?

I managed to do it using `getChildren(children, isElement)`, where `isElement` is from `react-is`, if that helps you understand.

**Comment by TheSpicyMeatball** [comment]
I think the way you did it is likely the best way unless there's a shortcoming with that which I'm missing?

**Comment by LoganDark** [comment]
Yeah, I solved my issue

**Comment by TheSpicyMeatball** [comment]
Cool, thanks for the clarification.
